### ISSUE TITLE
About detection criteria

### ISSUE THREAD

**Issue by rclai** [ptelad/react-native-iphone-x-helper#1]
Is the iPhone X the only phone with a height of [812](https://github.com/ptelad/react-native-iphone-x-helper/blob/24158e8abd4772075189db8384556ec966a5b04f/index.js#L10)? How reliable is this?

**Comment by rclai** [comment]
Nevermind, I guess Facebook [did the same thing](https://github.com/facebook/react-native/blob/04ff184c12e48f683c5758556917b7a41e7d2e65/React/Modules/RCTDeviceInfo.m#L106-L110).

**Comment by rogerkerse** [comment]
@rclai, I created js only library for this purpose https://github.com/boltss/react-native-safe-area-helper

It uses facebooks implementation and they have improved it so now even on iphone SE it says how much the inset is from status bar etc. It is not only iphonex fixed
