### ISSUE TITLE
Latest version doesn't support iPhone XR and XS Max

### ISSUE THREAD

**Issue by WienerGames** [ptelad/react-native-iphone-x-helper#12]
Hello, great lib, keep it up! 
However, it looks like there is problem with the latest version ("1.2.0"). We just installed it in order to obtain support for apple's new iPhones, but it only works for one of them (1 out of 3). Basically, the lib doesn't recognize iPhone XR and XS Max. It only works for iPhone XS. I hope you fix that asap, as we depend on it. Best of luck!

**Comment by zedtux** [comment]
I'm also looking for this !

**Comment by zedtux** [comment]
To fix this package, [this line](https://github.com/ptelad/react-native-iphone-x-helper/blob/master/index.js#L9) should be updated in order to add the new phones dimensions.

**Comment by zedtux** [comment]
Well, actually I just saw that [a PR exists](https://github.com/ptelad/react-native-iphone-x-helper/pull/9), so actually this issue is a **Bug** report.

**Comment by zedtux** [comment]
And finally I just figured out that I have not updated the package in my project. @WienerGames have you upgraded the package in your project?

**Comment by zedtux** [comment]
Upgrading the package fixed the issue for me ! Sorry for the noise ! 🙇

**Comment by ptelad** [comment]
I'm glad it's working for you now :)
