### ISSUE TITLE
Footer tab height not adjusted for iPhone XS Max 

### ISSUE THREAD

**Issue by drwasho** [ptelad/react-native-iphone-x-helper#14]
It is working for iPhone X and XS, just not Max.

![baae5b6d-db5f-47b6-ae59-8d9644ea2f27](https://user-images.githubusercontent.com/3887694/47260219-6408a200-d4fa-11e8-9f45-8dff9bb66cbb.png)

**Comment by ptelad** [comment]
Hi,

Did you update to version `1.2.0`?
It's the only version that supports the latest devices.

**Comment by drwasho** [comment]
@ptelad yes I have, and it worked a treat for iPhone XS but not XS Max.

**Comment by drwasho** [comment]
![image](https://user-images.githubusercontent.com/3887694/47324868-dc12cb80-d6a4-11e8-941c-ce11dc9184fe.png)

@ptelad it also seems as though the status bar height is wonky too.

**Comment by ptelad** [comment]
I am now 100% sure npm did not install the correct version for you.
Change the version in `package.json` to `^1.2.0` remove the lib from `node_modules` and run `npm i` please.

**Comment by drwasho** [comment]
Followed those steps, and while they fixed up the status bar, the footer is still a problem:

<img src="https://user-images.githubusercontent.com/3887694/47396856-e948bc80-d76f-11e8-8764-ee2c5daf9831.png" width="300" />

**Comment by ptelad** [comment]
I really don't know what the problem is because it is working fine on my end.
Can you please past here the styling for the footbar?
Also, can you check in the console if `isIphoneX()` returns true or not?

**Comment by drwasho** [comment]
Sorry @ptelad looks like the problem was on our end, thanks for your help in any case!
