### ISSUE TITLE
iPad Support 

### ISSUE THREAD

**Issue by adkenyon** [ptelad/react-native-iphone-x-helper#20]
The following iPad models need support for `getBottomSpace`

- iPad Pro (12.9-inch) (3rd generation)
- iPad Pro (11-inch)

Outside of using [react-native-device-info](https://github.com/react-native-community/react-native-device-info) I'm not sure how to infer these models from the standard react native library.

**Comment by ptelad** [comment]
Supporting this will introduce a native part for this lib (for reading the device model) which I'm not kin on doing at the moment, sorry.

**Comment by AndyHubert** [comment]
This looks like a solution: https://docs.expo.io/versions/latest/sdk/device/

**Comment by adkenyon** [comment]
Yeah, we're planning on using [react-native-safe-area#getCurrentSafeAreaInsets](https://www.npmjs.com/package/react-native-safe-area#get-currentsafeareainsets--safeareainsets)

**Comment by zabojad** [comment]
The best to use right now would be [react-native-safe-area-view](https://github.com/react-native-community/react-native-safe-area-view) and [react-native-safe-area-context](https://github.com/th3rdwave/react-native-safe-area-context).
