### ISSUE TITLE
Detect Android notches also?

### ISSUE THREAD

**Issue by harrisonlo** [ptelad/react-native-iphone-x-helper#21]

**Comment by lucky-c** [comment]
I think this one is a good idea.
Also, i think it is great to detect the soft navigation bar height and visibility on android too?

**Comment by ptelad** [comment]
Google added a great API for notches in Android P I think.
But it's much more complicated than the 1 notch on iPhones.
So it sounds like a completely different lib to me.

**Comment by slavikdenis** [comment]
I suggest to use https://github.com/react-native-community/react-native-device-info#hasNotch for this.
