### ISSUE TITLE
iPhone XS Max black space

### ISSUE THREAD

**Issue by XaviSmith** [ptelad/react-native-iphone-x-helper#22]
I'm running version 1.2.1 of the library, but whenever I run on an iPhone XS max, there's always a black space at the top of things unless i specify a marginTop of -getStatusBarHeight, however this messes up the styling for iPhoneX. Any idea what would cause something like this?

Pictures below to illustrate what it looks like on iPhoneX and iPhone Xs Max respectively

iPhoneX
<img width="345" alt="Screen Shot 2019-08-20 at 12 39 44 PM" src="https://user-images.githubusercontent.com/10490713/63366376-9b78f280-c347-11e9-96f9-f103ad84341d.png">

iPhone xs Max
<img width="346" alt="Screen Shot 2019-08-20 at 12 38 42 PM" src="https://user-images.githubusercontent.com/10490713/63366396-a03da680-c347-11e9-8e81-8fb71cb1e197.png">

**Comment by XaviSmith** [comment]
Sample of the relevant styling for a different screen doing the same thing:
```
var deviceHeight = Dimensions.get('window').height;

if (isIphoneX()) {
//iPhoneX_margin is set elsewhere to be 25px. Still doesn't work when I change it to getStatusBarHeight()

  deviceHeight = deviceHeight - iPhoneX_margin; 
}

background: {
    flex: 1,
    width: null,
    backgroundColor: 'rgba(0,0,0,0.1)',
    justifyContent: 'flex-start',
    alignItems:'flex-start',
    alignSelf:'flex-start',
    height: deviceHeight
  }
```

**Comment by ptelad** [comment]
I'm sorry, but I don't really understand what you are trying to achieve here with you styling.
Why so subtract the `iPhoneX_margin` from the height?

**Comment by jdnichollsc** [comment]
This is a better implementation instead of using styles to detect iPhoneX, etc => https://github.com/th3rdwave/react-native-safe-area-context
