### ISSUE TITLE
Don't work if use styled components with  react-native-splash-screen lib.

### ISSUE THREAD

**Issue by AndreyPatseiko** [ptelad/react-native-iphone-x-helper#23]
When I try use with styled components lib.
My service for common use **utils.js**
   
    import { isIphoneX } from 'react-native-iphone-x-helper';
    export { isIphoneX };

In my styles file for any component:
   
    import { isIphoneX } from '../utils';
    import styled from 'styled-components';

    export const Wrapper = styled.View`  
       marginTop: ${() => (isIphoneX() ? '20%' : 0)};
    `;

When I run application in first time, your function **isIphoneX** don't work, even after redrawing the screen. But after refresh application in DEV mode, all work fine. 

PS. If I use in my  **utils.js** code: 

    import { Dimensions, Platform } from 'react-native';
    export const isIphoneX = () => {
       const { height, width } = Dimensions.get('screen');
       return Platform.OS === 'ios' && (height === 812 || width === 812);
    };

All work fine

**Comment by ptelad** [comment]
Hi,

Can you be more specific on what is not working?

**Comment by AndreyPatseiko** [comment]
import { isIphoneX } from '../utils';
    import styled from 'styled-components';

    export const Wrapper = styled.View` 
      marginTop: ${() => (isIphoneX() ? '20%' : 0)};  <-- in first run app always got FALSE
    `;

After reload app work fine. Got true value.

**Comment by AndreyPatseiko** [comment]
The problem was not in your library.
Problem was in my integration [**react-native-splash-screen**](https://www.npmjs.com/package/react-native-splash-screen) lib.
If you use this libs you have to make sure that **[RNSplashScreen show]** run latest command in **AppDelegate.h** like said in react-native-splash-screen tutorial.

    - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
     {
       // ...other any code
 
       [RNSplashScreen show];  // right here in front of YES 
       return YES;
    }
 
After moving line from down all work fine.
