### ISSUE TITLE
TypeError: Cannot read property 'DEFAULT_BACKGROUND_COLOR' of undefined

### ISSUE THREAD

**Issue by HadisSharif** [ptelad/react-native-iphone-x-helper#26]
I ran a jest test for my component and the test failed. 
Error:
`
      36 |     navigationBarHeight: {
    > 37 |         height: (Platform.OS == 'ios' ? 45 : 40) + (Platform.OS !== 'web' ? getStatusBarHeight(true) : 0),
         |                                                                             ^
      38 |         paddingTop: Platform.OS === 'ios' ? getStatusBarHeight(true) - 10 : 0
      39 |     },
      40 |     navigationBarTransparent: {

      at Object.require [as StatusBar] (node_modules/react-native/Libraries/react-native/react-native-implementation.js:131:12)
      at StatusBar (node_modules/react-native-iphone-x-helper/index.js:23:18)`

**Comment by houman-sanati** [comment]
mocking the `getStatusBarHeight()` method will solve your issue :

```
jest.mock("react-native-iphone-x-helper", () => ({
  getStatusBarHeight: jest.fn()
}))
```
