### ISSUE TITLE
support new iphoneX models

### ISSUE THREAD

**Issue by juergengunz** [ptelad/react-native-iphone-x-helper#6]
do you plan to support the new iphone X models?

**Comment by andres-torres-marroquin** [comment]
The new height for XR and XS Max models is 896.

**Comment by doug-sheridan** [comment]
[PR submitted](https://github.com/ptelad/react-native-iphone-x-helper/pull/9)

**Comment by agusvazquez** [comment]
Yes! I think there are lots of heights for navigation bars and I'd be nice for this cool lib to support those different heights. Like adding a new method called getNavigationBarHeight()

**Comment by gxsshallot** [comment]
@agusvazquez You can use my repo [gaoxiaosong/react-native-pure-navigation-bar](https://github.com/gaoxiaosong/react-native-pure-navigation-bar). It is a navigation bar with pure javascript and has status bar / navigation bar / total bar height constant.

**Comment by MaxInMoon** [comment]
[PR merged](https://github.com/ptelad/react-native-iphone-x-helper/pull/9)

**Comment by lnfnunes** [comment]
@MaxInMoon NICE! 😃 shouldn't this issue be closed then!?
